### ISSUE TITLE
Unable to see anything

### ISSUE THREAD

**Issue by Knut80** [txxia/starbound-map#4]
Worlds look like this:

![sbmconfusion](https://user-images.githubusercontent.com/53875368/62646281-46ec7500-b94e-11e9-9905-5c408930df1a.jpg)

I've tried several different worlds, tick and un-ticking the boxes, zooming and scrolling. No change, not even a grid.

I don't understand what I'm doing wrong, please educate me.

**Comment by txxia** [comment]
The map is displayed in another pane which is missing from your screenshot. 
Try opening the `imgui.ini` beside the exe file and edit it like this (or simply delete it):
```
[Map View]
Pos=0,0
Size=400,400
Collapsed=0
```

**Comment by txxia** [comment]
I see what the problem is, the map view is hidden behind this window. Move the window a bit and you will see a tiny one behind it.

**Comment by Knut80** [comment]
Ah, I see! Thank you very much.
